### ISSUE TITLE
Is it possible to rename this? 

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [NOAA-ORR-ERD/NUCOS#10]
It's a bit confusing, what with:

* The Python version
* The JS version
* The desktop GUI

The Python version is called "pyNUCOS" -- maybe this one should be called jsNUCOS ?

Will that make a mess of things in npm?

-CHB

**Comment by JamesMakela-NOAA** [comment]
Yeah, I thought it should probably be jsNUCOS, but the name was already established.  Changing it now would require renaming the package in the package.json for all web clients that use it, which to my knowledge is just WebGnome, and the ADIOS Oil Database.  Any others?

**Comment by ChrisBarker-NOAA** [comment]
I think that's it. so not a big deal.

It also could be renamed at the repo level, without changing the name in npm. as npm only does JS, there's no need for the specification.

I used pynucos for conda-forge, as conda does handle packages for multiple languages, including JS (though not a lot of that now)

**Comment by ChrisBarker-NOAA** [comment]
Probably, but let's hold off for now.

**Comment by ChrisBarker-NOAA** [comment]
project renamed -- still "nucos" in NPM, but that's fine.
