### ISSUE TITLE
allow dots in unit names

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [NOAA-ORR-ERD/NUCOS#11]
sometimes people put dots in unit names, e.g.

`Pa.s`

for Pascal Seconds.

In PyNUCOS, this is handled with this function:

```
def Simplify(string):
    """
    Simplify(string)

    returns the string with the whitespace and capitalization removed
    """
    try:
        return "".join(string.lower().split()).replace(".", "")
    except AttributeError:
        raise NotSupportedUnitError(string)
```

Something like that would be good for jsNUCOS as well.

@james: as we talked about today.

**Comment by JamesMakela-NOAA** [comment]
Ok this is done in commit cfa664e

**Comment by PythonCHB** [comment]
thanks!

-CHB
