### ISSUE TITLE
Better support for partial latitude/longitude matches

### ISSUE THREAD

**Issue by naomiconnolly-noaa** [NOAA-ORR-ERD/NUCOS#2]
Example 1:
Lower case s for South doesn't work.

Example 2:
"-123 40 48" throws the error "Uncaught TypeError: Cannot read property '1' of null" but should be interpreted as "123 40 48S"

**Comment by ChrisBarker-NOAA** [comment]
So are you putting lat-lon string parsing into this? should I do the same on the py_nucos side??

no luck finding a liobrary for this? Here's one:

http://www.codeproject.com/Articles/15659/Longitude-Latitude-String-Parser-and-Formatter

(C#? ) -- probably not useful to port the code, but if nothing else, there is a set of formats it supports that we might want to copy.

-CHB

**Comment by naomiconnolly-noaa** [comment]
It was already there from py_nucos. It's just one way though, degrees min sec to decimal. I did look at a couple other solutions but in trying them out they weren't as flexible as this one already was. Use of this has already been implemented successfully for another project too.

**Comment by ChrisBarker-NOAA** [comment]
In Pyton, there is this:

https://pypi.python.org/pypi/LatLon/1.0.2

but doesn't look like it does "smart" parsing.

can't find anyting for javascript in google -- except really brain dead questions on SO :-)

**Comment by naomiconnolly-noaa** [comment]
Yeah take away from researching it is that's an easy enough problem to solve computationally it's just the flexibility of parsing we need.

**Comment by ChrisBarker-NOAA** [comment]
py_nucos isn't very smart about it though -- what we really need is a way for people to type in almost anything sensible, and get what they expect...

**Comment by ChrisBarker-NOAA** [comment]
yup :-)

**Comment by ChrisBarker-NOAA** [comment]
note that from floating point degrees to deg-min-sec is not so straightforward, due to floating point imprecision... see the kludges in py_nucos.

**Comment by naomiconnolly-noaa** [comment]
Example 3:
71.23W -> 71.23W doesn't turn value to negative

**Comment by ChrisBarker-NOAA** [comment]
if we're going to do this, we need a LOT of examples we can run tests on...

**Comment by naomiconnolly-noaa** [comment]
Yep, there's already a test framework setup for the project so it would just be a matter of listing them all out. Fun rainy day project :smile:

**Comment by ChrisBarker-NOAA** [comment]
This is pretty fully done now :-)

See #13 for the latest improvements
