### ISSUE TITLE
Can the UnitDict be loaded from a separate JSON file?

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [NOAA-ORR-ERD/NUCOS#5]
Ideally, the UnitDict would be in its own file, making it easier to maintain and update.

Also, ideally, it is kept in sync with pyNUCOS. pyNUCOS has a utility to output its unit dict as a JSON file, so we would ideally update stuff in pyNUCOS, and then us it to generate a JSON file for jsNUCOS.

**Comment by ChrisBarker-NOAA** [comment]
@JamesMakela-NOAA: is this done?

**Comment by JamesMakela-NOAA** [comment]
@ChrisBarker-NOAA: Well it is done, but I had to make a fix to make it work for WebGnome.  And now I noticed that fix has broken something when the ADIOS oil database client tries to use it.

**Comment by ChrisBarker-NOAA** [comment]
Darn.

OK -- when you've fixed tha, let's close this issue :-)

**Comment by ChrisBarker-NOAA** [comment]
This has been working for a while.
