### ISSUE TITLE
Python and Javascript synchronization

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [NOAA-ORR-ERD/NUCOS#6]
It would be nice to have better / more automatic syncronization between the Python and JS versions. A couple ideas:

* have both versions load the UnitData from a JSON file -- then that's one file to maintain.

* Keep both versions in the same repo: That would make it easier to keep them in sync.

* Any way to have the same tests? or at least tests from the same database of tests??

**Comment by ChrisBarker-NOAA** [comment]
@james: are we closer to this? maybe we can document it -- or automate it more.

**Comment by JamesMakela-NOAA** [comment]
@ChrisBarker-NOAA: Well right now it is a bit more seamless.  PyNUCOS can produce a .json file from its unit_data, and that file can now simply be copied to NUCOS to get the updates.  But there is not a single file that both projects use.

**Comment by ChrisBarker-NOAA** [comment]
well, we *could* set up a CI to go grab the unit_data json file from pyNUCOS ....

**Comment by ChrisBarker-NOAA** [comment]
I'm going to call this good enough for now.
